### ISSUE TITLE
[ROKU] Will not download even though paying for channel

### ISSUE THREAD

**Issue by Sipherdrakon** [stabbedbybrick/freevine#100]
**Describe the bug**
I paid for Discoveryplus through roku and it still is saying that payment is required to download.

**Expected behavior**
I put in login details as well as using cookies so it should realize it's paid for and download accordingly, but it doesnt.

Using this argument:

freevine.py get --episode "https://therokuchannel.roku.com/watch/64cc1a498c1c522e8060ec216ea989cf"

**Comment by stabbedbybrick** [comment]
Premium content isn't inherently supported. Hence the name, "Freevine".

**Comment by Sipherdrakon** [comment]
I do understand that , I just figured since freevine allowed for Roku login that it would work. 😃

If it doesn't that's fine, I can still pull the files old school, just figured I'd find out why it wasn't allowing download through freevine. 😃

**Comment by stabbedbybrick** [comment]
It does allow for credentials and cookies to be used, but the actual authentication is not implemented in the Roku script since you need to be a paid subscriber. So that would be something you could add yourself if you wanted.

**Comment by Sipherdrakon** [comment]
Okay cool, might give that a go then. 😃
