### ISSUE TITLE
Getting "Not authenticated" error with CTV

### ISSUE THREAD

**Issue by chris6611** [stabbedbybrick/freevine#25]
**Describe the bug**
Gettig the following error:
```
18:54:52.998 INFO : Freevine v1.0.5

18:54:53.158 INFO : CTV
18:54:53.573 INFO : Children Ruin Everything (2022): 3 Season(s), 33 Episode(s)

⠦ Getting media info...

18:54:54.183 ERROR : <Response [401]> Access denied. User is not authenticated
```

**To Reproduce**
1. Download the main branch
2. Run the following command: `python3 freevine.py --info -s S01 https://www.ctv.ca/shows/children-ruin-everything`
3. Get the above error.

**Expected behavior**
Expected information of Season 1 of the Children Ruin Everything show.

**Comment by cagenuts** [comment]
It's because S01 is locked and you have to sign in first but this script does not support this function.

**Comment by chris6611** [comment]
There is no way to pass a netscape cookie file to the script for authentication?

**Comment by stabbedbybrick** [comment]
S01 and S02 require subscription through a provider, which is currently not supported.

**Comment by chris6611** [comment]
> S01 and S02 require subscription through a provider, which is currently not supported.

I was going to close this issue then but don't know which option you'd like, so feel free to close it. Thanks for the reply.
