### ISSUE TITLE
Add `--proxy` support for initial requests

### ISSUE THREAD

**Issue by stabbedbybrick** [stabbedbybrick/freevine#28]
**Is your feature request related to a problem? Please describe.**
Many services only geoblock the API and license requests, while the actual downloads are not. Being able to use a proxy for that initial request would be less disruptive than having to change location locally.

**Describe the solution you'd like**
Being able to set proxy in config, or through a `--proxy` argument.
It would ideally support both specific servers and location requests like `--proxy "US"`

**Comment by Sal-Ammonite** [comment]
Just for info: On unix/linux (and I'd guess OS X too?), python respects the HTTP_PROXY and HTTPS_PROXY environment variables. Since `bash` etc. spawn a sub-shell that takes environment variables passed to it to run external commands, something like ...

`HTTP_PROXY=http://ip.addr.of.proxy:port HTTPS_PROXY=http://name.of.proxy.server:port <freevine command line>`

... works fine without affecting anything else.

**Comment by stabbedbybrick** [comment]
> Just for info: On unix/linux (and I'd guess OS X too?), python respects the HTTP_PROXY and HTTPS_PROXY environment variables. Since `bash` etc. spawn a sub-shell that takes environment variables passed to it to run external commands, something like ...
> 
> `HTTP_PROXY=http://ip.addr.of.proxy:port HTTPS_PROXY=http://name.of.proxy.server:port <freevine command line>`
> 
> ... works fine without affecting anything else.

Interesting, I hadn't considered that. Thanks for the info.

**Comment by Sal-Ammonite** [comment]
No worries; thank **_you_** for the scripts!.

I just also tried setting the environment variables using `os.environ` e.g. by adding
```
import os

os.environ['HTTP_PROXY'] = 'http://pro.xy.addre.ss:port'
os.environ['HTTPS_PROXY'] = 'http://pro.xy.addre.ss:port'
```
near the top of freevine.py, and that also worked. Not sure if it'd also work if set in the relevant scripts in utils/ and services/; at a guess it might depend on exactly when they're set in relation to when the requests/httpx libs are imported, the objects created, or they're called.

Another interesting thing: I run in a docker container with the environment variables for proxies (and others e.g. locale) pre-set. I'd have to double-check for sure, but a quick look at the traffic seems to show that inside freevine, N_m3u8DL-RE is also using the proxies for downloading.

edit: Ah, reading the N-m3u8DL-RE help, I see `--use-system-proxy` defaults to `true`.

**Comment by stabbedbybrick** [comment]
This feature was added in [v1.1.1](https://github.com/stabbedbybrick/freevine/releases/tag/v1.1.1)
