### ISSUE TITLE
Using `--save-dir` with iPlayer, Tubi on Windows returns `path empty`

### ISSUE THREAD

**Issue by stabbedbybrick** [stabbedbybrick/freevine#29]
**Describe the bug**
When using `--save-dir` to set save location on Windows, N_m3u8DL-RE `--mux-import` fails to read the path when importing subtitles on services like iPlayer and Tubi.

**Additional context**
v1.0.4 does not seem to have this error and can be used until this is fixed.

**Comment by stabbedbybrick** [comment]
This has now been fixed: https://github.com/stabbedbybrick/freevine/commit/5a00c5ea133b118bdcde1b55589f514f9e9448bc

**Comment by billybanana80** [comment]
Thanks for fixing this one 👍
