### ISSUE TITLE
Request: ITVX 1080p

### ISSUE THREAD

**Issue by Maverick20256** [stabbedbybrick/freevine#31]
Request: ITVX 1080p to be added please

1080p mpds can be obtained from tv so if we can add the 1080p mpd to freevine and then using l1 cdm to get keys that would be great :)

also adding support for downloading 4k hdr from iplayer would be good to :)

**Comment by stabbedbybrick** [comment]
Considering how rare true L1 access is, it feels like an addition that would benefit no one. I'd assume anyone with L1 CDM would be using their own scripts anyway.  

As for iPlayer 4k, I've thought about it. It's not particularly difficult, but it requires additional certification that I'm not so sure is a good idea to put up on a public repo. It might end up ruining the fun for everyone.

**Comment by Maverick20256** [comment]
> Considering how rare true L1 access is, it feels like an addition that would benefit no one. I'd assume anyone with L1 CDM would be using their own scripts anyway.
> 
> As for iPlayer 4k, I've thought about it. It's not particularly difficult, but it requires additional certification that I'm not so sure is a good idea to put up on a public repo. It might end up ruining the fun for everyone.

welling adding support for 1080p for itvx would be great addition!! and so would adding 4k hdr support for iplayer, 4k hdr support is available in VT but that sometimes has issues so having a backup would be good, also can u update tool to download 1080p from RTE Player plz thanks

**Comment by Maverick20256** [comment]
> Considering how rare true L1 access is, it feels like an addition that would benefit no one. I'd assume anyone with L1 CDM would be using their own scripts anyway.
> 
> As for iPlayer 4k, I've thought about it. It's not particularly difficult, but it requires additional certification that I'm not so sure is a good idea to put up on a public repo. It might end up ruining the fun for everyone.

VT Can download 4k hdr from iplayer etc
