### ISSUE TITLE
Plex.tv support

### ISSUE THREAD

**Issue by entrider** [stabbedbybrick/freevine#36]
Please consider adding support for [watch.plex.tv](https://watch.plex.tv/), imo it's quite good in terms of selection (compared to other free services) and it's DRM-free, the quality is limited to 720p though.

**Comment by stabbedbybrick** [comment]
Looks like they do have a pretty fun selection. Like a mix of Tubi and Crackle. 

I'll definitely look into it.

**Comment by entrider** [comment]
Apparently some titles are DRM-protected, e.g. https://watch.plex.tv/movie/second-sight-2016

**Comment by stabbedbybrick** [comment]
This has now been added in the latest update.
