### ISSUE TITLE
Sometimes doesn't pick best quality for SD shows on BBC iPlayer

### ISSUE THREAD

**Issue by JohnVeness** [stabbedbybrick/freevine#37]
With https://www.bbc.co.uk/iplayer/episode/p00vbb6n/doctor-who-19631996-season-22-vengeance-on-varos-part-2 (an old standard definition episode) with freevine.py with default config, the resultant video file is 704x396 pixels. Downloading the same with get_iplayer with default config results in a video file of 960x540 pixels.

According to get_iplayer --info, there are three qualities of this episode, "sd, web, mobile". get_iplayer is downloading the "sd" quality version, but it seems freevine is downloading the lower "web" quality version.

**Comment by JohnVeness** [comment]
Trying ```freevine.py --select-video res=540 --episode https://www.bbc.co.uk/iplayer/episode/p00vbb6n/doctor-who-19631996-season-22-vengeance-on-varos-part-2``` gives
```
21:41:06.613 INFO : Freevine v1.0.6

21:41:06.984 INFO : BBC iPlayer
Traceback (most recent call last):
  File "/home/john/coding/freevine/freevine.py", line 36, in <module>
    main()
  File "/home/john/venv/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/venv/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/john/venv/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/venv/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/coding/freevine/utils/commands.py", line 39, in wrapper
    return command(search=search, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/coding/freevine/freevine.py", line 30, in main
    Service(main_config, service_api, service_config, **kwargs)
  File "/home/john/coding/freevine/services/bbciplayer/bbciplayer.py", line 49, in __init__
    self.get_options()
  File "/home/john/coding/freevine/services/bbciplayer/bbciplayer.py", line 323, in get_options
    self.download(download, title)
  File "/home/john/coding/freevine/services/bbciplayer/bbciplayer.py", line 363, in download
    self.res = self.get_mediainfo(soup, self.quality)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/coding/freevine/services/bbciplayer/bbciplayer.py", line 241, in get_mediainfo
    closest_match = min(heights, key=lambda x: abs(int(x) - int(quality)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence
```

**Comment by stabbedbybrick** [comment]
The current iteration of the iPlayer script is somewhat limited in scope, so sometimes it'll miss higher quality versions or select the descriptive audio. 

Updates are kind of slow at the moment, but I definitely intend on improving this.

**Comment by cagenuts** [comment]
@595974 It may be because in your config.yaml there's a setting for best audio. The 396p video has 128k audio whilst the 540p has 96k. If you are connecting from outside the UK then you don't get all the available streams. I'm not saying ALL 540p streams have 96k audio but some do. This particular one is DASH whilst normally the HLS streams have 128k audio. So first download with `-sv res=540 -sa for=worst `and then download the 396p to get 128k audio. Extract the audio or use ffmpeg to use the audio stream from the 396p video and create a new container with 540p video + 128k audio,

**Comment by JohnVeness** [comment]
Ah thanks, that's interesting. For info I am connecting inside the UK (genuinely, no VPN).

Unfortunately, as I said in https://github.com/stabbedbybrick/freevine/issues/37#issuecomment-1856686110 , for some reason the ```--select-video``` aka ```-sv``` option doesn't seem to work for me.

**Comment by stabbedbybrick** [comment]
The latest update should bring some improvement to this. It's not perfect, but there's a much bigger chance of it catching the highest quality stream now. Except for 2160p that is, which is still a work in progress.

**Comment by JohnVeness** [comment]
Thanks! Yes, I can confirm that ```python3 freevine.py get -e https://www.bbc.co.uk/iplayer/episode/p00vbb6n/doctor-who-19631996-season-22-vengeance-on-varos-part-2``` now gets the 540p version by default.

Also the -sv option works for me now too :)
