### ISSUE TITLE
Load list of URLs to download from file

### ISSUE THREAD

**Issue by OevreFlataeker** [stabbedbybrick/freevine#44]
I'd like to request the feature to allow for a batch downloading of several URLs in one go.
Sometimes I don't want to download a whole Season and just 1 or 2 episodes from a new series to check it out. 
I'd like to put the URLs in a file and have that downloaded by freevine.py (Yes, the provisioning of the URLs could as well happen from the outside ;-) .

**Comment by stabbedbybrick** [comment]
It's already been added to the main branch. Put the commands in a text file and provide it to freevine with `file` command:

`freevine.py file "path/to/file.txt"`

Text file:
```
get -e s01e01 https://example.dom
get -e s01e01 https://example2.dom
get -e s01e01 https://example3.dom
```

But why not just not download those particular episodes with `-e s01e01` like normal?

**Comment by OevreFlataeker** [comment]
Thanks! Didn't notice, will check this out. The idea was to have a longer list of streams to download one after the other, automatically potentially over night.
