### ISSUE TITLE
1080p L1 Support for itvx

### ISSUE THREAD

**Issue by Maverick20256** [stabbedbybrick/freevine#61]
Please add the option to add 1080p L1 Support for downloading/decrypting from itvx

**Comment by stabbedbybrick** [comment]
Not going to happen.

**Comment by Maverick20256** [comment]
> Not going to happen.

and why not you have added 1080p for others? ......................

**Comment by PlaceboPRS** [comment]
> > Not going to happen.
> 
> and why not you have added 1080p for others? ......................

L1 is the issue isn't it? Hardware only AFAIK.

Other sources don't require L1 for 1080p, big difference.

**Comment by Maverick20256** [comment]
> > > Not going to happen.
> > 
> > 
> > and why not you have added 1080p for others? ......................
> 
> L1 is the issue isn't it? Hardware only AFAIK.
> 
> Other sources don't require L1 for 1080p, big difference.

yes but i have working l1 cdm i can use for that but dont have tool to get the 1080p files

**Comment by Maverick20256** [comment]
i can download and decrypt 1080p from itvx now anyways :) MY OWN WAY!
