### ISSUE TITLE
Item added to cache even if it fails

### ISSUE THREAD

**Issue by c-hri-s** [stabbedbybrick/freevine#63]
I've been trying to download a series from C4 and coming up against the issues in https://github.com/stabbedbybrick/freevine/issues/56

I've tried the new version using the timeout and threads 1 and this improves things, however I'm still bumping up aganst the rate limiting.

The issue is that for some videos it downloads the subtitle file successfully and then thinks it's downloaded the episode, so when you rerun the script it doesn't try again.

Please could you make it so it only adds the item to the cache if the **video** download completes?

Tested with `freevine.py get --slowdown 120 --threads 1 --complete https://www.channel4.com/programmes/the-great-celebrity-bake-off-for-su2c`

**Comment by stabbedbybrick** [comment]
Both this issue and https://github.com/stabbedbybrick/freevine/issues/64 should already be fixed in the main branch, and will be included in the next version.

**Comment by c-hri-s** [comment]
Thanks. Seems fixed in 1.14
