### ISSUE TITLE
Narrator is on for all downloads

### ISSUE THREAD

**Issue by Glorithan** [stabbedbybrick/freevine#71]
I have downloaded multiple movies and series from Pluto and the narrator is on for them.

1. Download anything using freevine. This is the command I used to download the Sonic movie this morning.
     - .\freevine.py get --movie https://pluto.tv/en/on-demand/movies/635c1e430888bc001ad01a9b

Expected is for it to download without the narrator

No errors occur to screenshot

**Comment by Glorithan** [comment]
I assume there is some kind of argument I can add to the command to turn off narrator, I just cant find it in the help or previous issues.

**Comment by PlaceboPRS** [comment]
Simplest solution is to use -sa all and it'll download all audio tracks then in your media player just switch the audio track.

freevine.py get --movie -sa all https://pluto.tv/en/on-demand/movies/635c1e430888bc001ad01a9b

Sometimes the narrated audio track is slightly bigger than the other audio track so it considers it best, or sometimes it'll be the first track, yet on another provider the second audio track.

**Comment by Glorithan** [comment]
That solves my issue. Tested with the same movie and now I can change to the 2nd English option and there is no narrator. Thanks for the quick help!
