### ISSUE TITLE
Plex TV Audiotrack selection

### ISSUE THREAD

**Issue by easy20192018** [stabbedbybrick/freevine#76]
**Describe the bug**
I'm having trouble downloading Plex Free Movies. The film only comes with an English audio track. But I can see the German audio track via the browser. 

Freevine last GIT-Trunk

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PlaceboPRS** [comment]
Where's the steps to repro? At least share the specific URL to something?

You can try adding -sa all to download all audio tracks...

**Comment by easy20192018** [comment]
https://watch.plex.tv/de/movie/cube2-hypercube

its show only english audio in the app.  In the browser can switch english or german.

**Comment by stabbedbybrick** [comment]
This has been fixed in the latest commit. Pull the new updates and all available languages should be included.

**Comment by easy20192018** [comment]
thanks. Its  works.
