### ISSUE TITLE
Support RTE Player

### ISSUE THREAD

**Issue by swannie-eire** [stabbedbybrick/freevine#86]
**Describe the solution you'd like**
Support for RTE Player.

https://www.rte.ie/player/

RTE player is a Free streaming service provided by Irish public media broadcaster RTÉ

**Comment by stabbedbybrick** [comment]
It's been added to main branch with the latest PR: https://github.com/stabbedbybrick/freevine/pull/87

**Comment by swannie-eire** [comment]
Thank you
