### ISSUE TITLE
CTV subs

### ISSUE THREAD

**Issue by FuNFooKaS** [stabbedbybrick/freevine#88]
**Describe the bug**
after the update today, it seems the subs are being skipped

**To Reproduce**
 ```
Highway Thru Hell S12E04 Killer's Corner

05:48:23.957 INFO : Subtitles: https://capi.9c9media.com/destinations/discovery_hub/platforms/desktop/playback/contents/2729825/contentPackages/6088632/manifest.vtt
05:48:24.143 WARNING : Subtitle response 401, skipping
```
tried a few diff shows and all the same

**Additional context**

**Comment by cagenuts** [comment]
Looks like these episodes are only available with a TV login. See the lock sign.

**Comment by stabbedbybrick** [comment]
Since this was fixed in this commit: https://github.com/stabbedbybrick/freevine/commit/54cac0e1ed90723ca21867b5cd56774ead3cdb1c, I'll close this as completed
