### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by saintyuk** [stabbedbybrick/freevine#98]
**Is your feature request related to a problem? Please describe.**
No not at all.

**Describe the solution you'd like**
Maybe something along the lines of: `freevine.py search * "test"`

**Describe alternatives you've considered**
For now this can be used, although it's a pain to keep up with all the new services :)
`freevine.py search abciview,bbciplayer,cbc,cbs,channel4,channel5,crackle,ctv,cwtv,itv,plex,pluto,roku,rte,stv,svtplay,tubi,tv4play,tvnz,uktvplay "test"`

**Additional context**
N/A

**Comment by stabbedbybrick** [comment]
This is a good suggestion, and something I've been thinking about adding ever since the services started to grow. 

It's definitely on the to-do list.

**Comment by stabbedbybrick** [comment]
This has been added in https://github.com/stabbedbybrick/freevine/commit/9c0235c378ead9b583763718cbe4d3182800d0c5

You can now use `freevine.py search all "query"` to search all services.

**Comment by saintyuk** [comment]
Superb. Thanks very much :)

**Comment by PlaceboPRS** [comment]
Awesome! Is there a trick to searching for something consisting of two words please? E.g. I'm looking for anything with the comedian Paul Foot but when I search "Paul Foot" it's failing:

![image](https://github.com/stabbedbybrick/freevine/assets/23120453/9093d758-bd50-4c9d-b5da-26cbdb054e59)

**Comment by saintyuk** [comment]
@PlaceboPRS Seems to be a problem specifically with _channel4_ & _svtplay_. Both don't seem to cope with multiple words.

To confirm this try using ever other service except those two:
`freevine.py search abciview,bbciplayer,cbc,cbs,channel5,crackle,ctv,cwtv,itv,plex,pluto,roku,rte,stv,tubi,tv4play,tvnz,uktvplay "Paul Foot"`

**Comment by stabbedbybrick** [comment]
> Awesome! Is there a trick to searching for something consisting of two words please? E.g. I'm looking for anything with the comedian Paul Foot but when I search "Paul Foot" it's failing:

Multiple keywords work fine, the issue was with a couple of services returning a different response in case of no matches. But it should be fixed in the latest commit.

**Comment by saintyuk** [comment]
Tested and spot on. Following command now works perfectly! 

Cheers @stabbedbybrick 

`freevine.py search all "Paul Foot"`

**Comment by PlaceboPRS** [comment]
Works a treat now thank you! I hate to ask this sorry to sound demanding, wondered if there's any way to force results that only have both words e.g. "Paul+Foot"? Right now it's returning all results with Paul and all with Foot...

![image](https://github.com/stabbedbybrick/freevine/assets/23120453/78a599dd-2444-4c9f-97e8-6c07cc4b3e55)

**Comment by stabbedbybrick** [comment]
@PlaceboPRS: 

How they match the query is up the API of whatever site you're searching. You could try using AND, like `Paul AND Foot`, but in most cases the results will be relatively fuzzy. Not much to do about it.

**Comment by PlaceboPRS** [comment]
Aha ok I fully understand! I already found some good leads with the search so thank you for that! :)
